### ISSUE TITLE
Single source of dependencies

### ISSUE THREAD

**Issue by dekoza** [pre-commit/mirrors-eslint#18]
Is there a way to point this hook (or eslint) to package.json to collect all its dependencies instead of repeating them in `additional_dependencies`? If not, let it be my feature-request :smile:

**Comment by asottile** [comment]
there is not, and it won't be implemented (the caching problem becomes intractable).  pre-commit's design is very careful about only installing from files it manages such that it can provide a fast and correct experience

there's quite a few more issues about this on the main tracker (search for requirements.txt or package.json) https://github.com/pre-commit/pre-commit/issues

there's also a few workarounds there (like making a `language: script` which runs `npm i` followed by `node_modules/.bin/...`) -- though you immediately lose most of the benefits of the framework

**Comment by dekoza** [comment]
OK, thanks for fast answer.
