### ISSUE TITLE
Doesn't pick up .eslintrc.js config file

### ISSUE THREAD

**Issue by ogomozov-godaddy** [pre-commit/mirrors-eslint#27]
I have standard `.eslintrc.js` config file, which works with husky hooks and regular eslint run
However, when I run via `pre-commit` tool, it ignores this file. No rules or other changes are picked up. Here is my yaml below.
```
  -   repo: https://github.com/pre-commit/mirrors-eslint
      hooks:
      -   id: eslint
          files: \.[jt]sx?$
          additional_dependencies:
          -    eslint-loader
          -    eslint-plugin-json
          -    eslint-plugin-jsx-a11y
          -    eslint-plugin-react
          -    eslint-plugin-react-hooks
```

 I wonder, how to use yaml config to pass down params to eslint? Can I use standard props of eslint CLI? For instance, i tried to use `config` to use this file, but it wasn't recognized

```
  -   repo: https://github.com/pre-commit/mirrors-eslint
      hooks:
      -   id: eslint
          files: \.[jt]sx?$
          config: .eslintrc.js
          additional_dependencies:
          -    eslint-loader
          -    eslint-plugin-json
          -    eslint-plugin-jsx-a11y
          -    eslint-plugin-react
          -    eslint-plugin-react-hooks
```

**Comment by asottile** [comment]
can you elaborate on what you mean "works" and "doesn't work" -- please show an example.

fwiw it's working great for me here: https://github.com/pre-commit/pre-commit.com/blob/edc4da2fd3c22ff1560c1b46e743a1d15a333dec/.pre-commit-config.yaml#L41-L45

**Comment by ogomozov-godaddy** [comment]
eslint allows to use different configs: JSON\JS file ` .eslintrc.*` or `eslintConfig` inside `pqckage.json` by default
https://eslint.org/docs/user-guide/configuring
In other project I use husky https://github.com/typicode/husky/tree/master and my script looks looks like
```
// package.json
{
  "husky": {
    "hooks": {
      "pre-commit": "eslint --fix ."
    }
  }
}
```
which uses `.eslintrc.js` from same folder as config. However, when I put this file in new project folder and run `pre-commit run -all-files` it constantly reports rules I didn't setup in this file. I also tried:
1) use `args: [--config, .eslintrc.js]` in yaml to provide path to config file
2) pre-commit clean and pre-commit install-hooks to clean up hooks configuration and cache so it picks new config in yaml and may be `.eslintrc.js`

but it contantly reports rule, which I am sure cleaned up from `.eslintrc.js` and even anything related in yaml (eslint deps, plugins, etc). It seems like it's not only eslint config, but overall precommit hooks.
I see errors about `@godaddy/react-intl/id-missing` rule, which I may have had in my files when first running. Now I made eslint hooks as simple as possible, no rules, no deps, no plugins, and still see this rule error

**Comment by ogomozov-godaddy** [comment]
I run with below config and see `@godaddy/react-intl/id-missing` rule error. Where does it come from?

```
  -   repo: https://github.com/pre-commit/mirrors-eslint
      rev: ''  # Use the sha / tag you want to point at
      hooks:
      -   id: eslint
          files: \.[jt]sx?$
```

**Comment by asottile** [comment]
can you share a small reproducible example?  basically file contents I can copy and run myself?  also showing command line outputs would be helpful too

**Comment by ogomozov-godaddy** [comment]
I found my issue. I had another config of `eslintConfig` inlined in package.json, which prevailed over any other config files
