### ISSUE TITLE
Describe how to set up eslint config

### ISSUE THREAD

**Issue by dfrankow** [pre-commit/mirrors-eslint#29]
Thanks for your work on this project.

If I follow your basic instructions, and run pre-commit, I get an error that there's no config:

```
$ pre-commit run --file blah/foo.js -v
...
Oops! Something went wrong! :(

ESLint: 7.22.0

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in blah and its ancestors. If it found none, it then looked in your home directory.
```

If I try `eslint`, it's not in my path. So I think pre-commit is running it from somewhere, and I have to figure out where. Now I'm digging around.

I think a few more instructions in the README might help me considerably.

**Comment by dfrankow** [comment]
Looks like eslint is installed in a cache somewhere. In this example, it was:

```
~/.cache/pre-commit/repo5jix1yed/node_env-system/bin/eslint
```

I used this command to find it:

```
find ~ -name "*eslint*"
```

**Comment by asottile** [comment]
ah, I believe the expectation for setting up an eslint configuration is to use an existing configuration?  for me I found this one in the documentation: https://github.com/pre-commit/pre-commit.com/blob/1ccab4e20154e13621b3a7c676f2c85b556ae3c6/package.json#L7-L29

`eslint --init` is a convenience to write out that bit of json for you and isn't necessary for operation

**Comment by dfrankow** [comment]
I found it quite useful to run `eslint --init`, since it asked a bunch of questions about our project, and produced a config more suitable for us. So I'd recommend it over taking a random config.

Here is the `.eslintrc.yml` I ended up with, for reference:

```
env:
  browser: true
  es2021: true
  jquery: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {}
```
