### ISSUE TITLE
Should not run on ignored files

### ISSUE THREAD

**Issue by flying-sheep** [pre-commit/mirrors-eslint#33]
When ignoring a file, running pre-commit yields

> `0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override`

That happens when you run `eslint` on a file specifically instead of passing glob patterns to it: https://github.com/eslint/eslint/issues/5623

There seems to be no way to suppress this warning specifically, it will be raised whenever eslint’s file traversal encounters an ignored file: https://github.com/eslint/eslint/blob/a1f7ad77e2da00ac7d6daade547fe6bef4ef6003/lib/cli-engine/cli-engine.js#L778-L782

And it does that whenever it’s passed a path that is not a glob pattern: https://github.com/eslint/eslint/blob/a1f7ad77e2da00ac7d6daade547fe6bef4ef6003/lib/cli-engine/file-enumerator.js#L356-L371

We can easily solve this for `--all-files` by just running `eslint .` and letting it do the rest, but the only possible solutions for uses is:

1. Adding a way to make ESLint not emit a warning when directly passing an ignored path
2. Parsing the ignore file ourselves and removing ignored files from any change list passed to ESLint

The first alternative is vastly simpler, it’s a 2 line change in ESLint.

**Comment by asottile** [comment]
use pre-commit's `exclude`

**Comment by flying-sheep** [comment]
It’s not DRY but currently seems to be the only option.

Once https://github.com/eslint/eslint/issues/15010 if fixed, we can make `pre-commit` use the new command line option.
