### ISSUE TITLE
Compatibility with `plugin:@typescript-eslint/recommended-requiring-type-checking`

### ISSUE THREAD

**Issue by coler-j** [pre-commit/mirrors-eslint#38]
Is there any way to get this compatible with https://typescript-eslint.io/linting/typed-linting/?

I think it would need access to ALL dependencies (and their types) from the project which seems like the additional dependencies array would then be pointless.

**Comment by asottile** [comment]
type checkers are far too slow to be used for quick checks -- I wouldn't recommend it but yes `additional_dependencies` would be where you specify your deps

**Comment by coler-j** [comment]
Ok yes, I am now trying to disable my typed check within the pre-commit workflow. Will post approach shortly once I figure out how.
