### ISSUE TITLE
Support private npm registires

### ISSUE THREAD

**Issue by saada** [pre-commit/mirrors-eslint#41]
I saw this ticket was closed and locked https://github.com/pre-commit/mirrors-eslint/issues/35.
I tried to reopen it in https://github.com/pre-commit/mirrors-eslint/issues/40 and it was quickly shut down.
Would like to reopen it as I'm facing the same issue and it's definitely not resolved.

Happy to be on my own with some guidance.

There are no solutions in that thread. We can call them suggestions and hacks that don't work.
Is this a feature I could build and contribute?

Can you please not mute the conversation again and allow dialogue to happen?

**Comment by asottile** [comment]
"does not work" is not a bug report. there are solutions you just seem to not like them for some reason
