### ISSUE TITLE
limit js checked by directory

### ISSUE THREAD

**Issue by sfahlberg** [pre-commit/mirrors-eslint#7]
Hi there,
I want to be able to run eslint like this `eslint --ext .jsx --ext .js ./webpack/app/**`. The jsx is easy to do, but how can I limit the js files checked to just those at `./webpack/app/**`?

**Comment by sfahlberg** [comment]
nevermind, I discovered that I can use `args` in my config file

**Comment by asottile** [comment]
You can also use `files:` or `exclude:` to control what files get passed to the hook as well: http://pre-commit.com/#plugins

**Comment by sfahlberg** [comment]
files worked better- just a little bit of regex, and voila! thanks!

**Comment by asottile** [comment]
No problem :) glad to help!
