### ISSUE TITLE
issue running linter

### ISSUE THREAD

**Issue by sfahlberg** [pre-commit/mirrors-eslint#8]
Hi there, for some reason I'm getting this error. I wonder if we need to update the eslint version to 3.18 from 3.14? I don't get this error when I run it in my browser.

```
The react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.
/Users/sam/bb/clarity/.eslintrc:
	Configuration for rule "import/no-extraneous-dependencies" is invalid:
	Value "**/*.test.js" is the wrong type.

Error: /Users/sam/bb/clarity/.eslintrc:
	Configuration for rule "import/no-extraneous-dependencies" is invalid:
	Value "**/*.test.js" is the wrong type.
```

my .eslintrc looks like this:
```
"import/no-extraneous-dependencies": [
      "error",
      {
        "devDependencies": ["**/*.test.js"]
      }
    ],
```

my pre-commit-config.yaml looks like this:

```
-   repo: git://github.com/pre-commit/mirrors-eslint
    sha: v3.9.1
    hooks:
    -   id: eslint
        files: (webpack\/app\/.*\.js|\.jsx)$
        stages: [push]
```

**Comment by asottile** [comment]
I've pushed tags for all the versions that weren't there yet (v3.14.1->v3.18.0) -- does upgrading to a new version (perhaps via `pre-commit autoupdate --tags-only`) work?

**Comment by asottile** [comment]
@sfahlberg does the new version work for you?

**Comment by sfahlberg** [comment]
yup- appears to be working. thanks!

**Comment by asottile** [comment]
Nice!

**Comment by sfahlberg** [comment]
having the same issues again today. my pre-commit-config.yaml looks like this now: ```
-   repo: git://github.com/pre-commit/mirrors-eslint
    sha: v3.18.0
    hooks:
    -   id: eslint
        files: (webpack\/app\/.*\.js|\.jsx)$
        stages:
        - push
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: detect-private-key
        stages:
        - push
    -   id: check-merge-conflict
        stages:
        - push
    -   id: detect-aws-credentials
        stages:
        - push
-   repo: git://github.com/pricematch/mirrors-rubocop
    sha: empty
    hooks:
    -   id: rubocop
        stages:
        - push
-   repo: local
    hooks:
    -   id: mocha
        name: mocha
        entry: npm run mocha
        language: system
        files: (webpack\/app\/.*\.js|\.jsx)$
        stages:
        - push
-   repo: git://github.com/pre-commit/mirrors-eslint
    sha: v3.18.0
    hooks:
    -   id: eslint
        files: (webpack\/app\/.*\.js|\.jsx)$
        stages:
        - push
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: detect-private-key
        stages:
        - push
    -   id: check-merge-conflict
        stages:
        - push
    -   id: detect-aws-credentials
        stages:
        - push
-   repo: git://github.com/pricematch/mirrors-rubocop
    sha: empty
    hooks:
    -   id: rubocop
        stages:
        - push
-   repo: local
    hooks:
    -   id: mocha
        name: mocha
        entry: npm run mocha
        language: system
        files: (webpack\/app\/.*\.js|\.jsx)$
        stages:
        - push
```

error looks like:
```The react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.
  4 || .eslintrc:
  5 ||         Configuration for rule "import/no-extraneous-dependencies" is invalid:
  6 ||         Value "**/*.test.js" is the wrong type```

**Comment by asottile** [comment]
(A bit out of scope for pre-commit but I'll try and help anyway!)

I imagine you need to change your `.eslintrc` to something like 

```json
{
    "...": "...",
    "import/no-extraneous-dependencies": ["error", {"devDependencies": ["**/*.test.js"]}],
    "...": "..."
}
```

I don't really know though, this sounds like more of an upstream problem since pre-commit is simply wrapping the `eslint` tool -- does `eslint` itself work for you?

**Comment by sfahlberg** [comment]
yeah, normal eslint works, it's just when I use pre-commit that I get this issue

**Comment by asottile** [comment]
what version of eslint are you using outside of pre-commit and how are you invoking it?

**Comment by sfahlberg** [comment]
`eslint -v` is `v3.7.0` and running it like so: `eslint --ext .jsx --ext .js ./webpack/app/**`

**Comment by sfahlberg** [comment]
should the sha for this repo be v3.7.0?

**Comment by asottile** [comment]
Ah well if you're running 3.7.0 outside pre-commit and 3.18.0 inside pre-commit you're bound to get different results

**Comment by sfahlberg** [comment]
there we go- seems to be working now. sorry about that. I didn't understand the documentation. I was using the version number for this repo, not for my eslint

**Comment by asottile** [comment]
👍 nice!
